import { InstrumentoMetadata } from './mediador.types';

export class XlsParser {
  /**
   * Parses the HTML/XLS table generated by the Mediador.
   * Handles the ISO-8859-1 (latin1) encoding and malformed <tr> structures.
   */
  static parse(html: string): InstrumentoMetadata[] {
    const parts = html.split(/<tr/gi);
    const instruments: InstrumentoMetadata[] = [];

    for (const part of parts) {
      // Look for rows with the indice attribute
      const trMatch = part.match(/^\s+indice="([^"]+)"[^>]*>([\s\S]*)$/i);
      if (!trMatch) continue;

      const content = trMatch[2];

      // Extract cells <td>
      const tdRegex = /<td[^>]*>([\s\S]*?)<\/td>/gi;
      const tds: string[] = [];
      let tdMatch;
      while ((tdMatch = tdRegex.exec(content)) !== null) {
        tds.push(
          tdMatch[1]
            .replace(/<[^>]*>/g, '') // remove HTML tags
            .trim()
            .replace(/\s+/g, ' ') // normalize spaces
        );
      }

      // Column structure in XLS export:
      // 0: Nº do Registro (e.g. DF000003/2026)
      // 1: Nº do Processo (e.g. 47979.284551/2025-99)
      // 2: Nº da Solicitação (e.g. MR072140/2025)
      // 3: Tipo de Instrumento Coletivo (e.g. Acordo Coletivo)
      // 4: Vigência (e.g. 01/10/2024 - 31/08/2026)
      // 5: CNPJ Trabalhador
      // 6: Trabalhador (Sindicato)
      // 7: CNPJ Empregador
      // 8: Empregador
      // 9: Nº Trab. Entidade(s)
      // 10: Nº Trab. Negociação
      instruments.push({
        numeroRegistro: tds[0] || '',
        numeroProcesso: tds[1] || '',
        numeroSolicitacao: tds[2] || '',
        tipoInstrumento: tds[3] || '',
        vigencia: tds[4] || '',
        cnpjTrabalhador: tds[5] || '',
        trabalhador: tds[6] || '',
        cnpjEmpregador: tds[7] || '',
        empregador: tds[8] || '',
        numTrabEntidades: tds[9] || '',
        numTrabNegociacao: tds[10] || ''
      });
    }

    return instruments;
  }

  /**
   * Helper to parse date string in format "DD/MM/YYYY" to Date object
   */
  static parseDate(dateStr: string): Date | null {
    if (!dateStr) return null;
    const parts = dateStr.trim().split('/');
    if (parts.length === 3) {
      const day = parseInt(parts[0], 10);
      const month = parseInt(parts[1], 10) - 1;
      const year = parseInt(parts[2], 10);
      if (!isNaN(day) && !isNaN(month) && !isNaN(year)) {
        return new Date(year, month, day);
      }
    }
    return null;
  }

  /**
   * Splits a vigência range string (e.g. "01/10/2024 - 31/08/2026") into start and end dates
   */
  static parseVigencia(vigenciaStr: string): { inicio: Date | null; fim: Date | null } {
    const defaultRes = { inicio: null, fim: null };
    if (!vigenciaStr) return defaultRes;

    const parts = vigenciaStr.split('-');
    if (parts.length === 2) {
      return {
        inicio: this.parseDate(parts[0]),
        fim: this.parseDate(parts[1])
      };
    }
    return defaultRes;
  }

  /**
   * Extracts UF from the registration number (first 2 characters)
   */
  static extractUf(numeroRegistro: string): string | null {
    if (!numeroRegistro || numeroRegistro.length < 2) return null;
    const uf = numeroRegistro.substring(0, 2).toUpperCase();
    // Validate if it is a valid state code
    if (/^[A-Z]{2}$/.test(uf)) {
      return uf;
    }
    return null;
  }
}
